spring:
  application:
    name: Imooc-Pasbook
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnect=true&serverTimezone=UTC
    username: root
    password: '00000000'
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 127.0.0.1:2181
      rootDir: file:///Users/chrischen/Documents/hbase-1.4.13/hbase_data
      nodeParent: /hbase
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 9528

logging:
  file: imooc-passbook.log
  level: debug